TrulyNatural SDK: SnsrStream Class Reference
SnsrStream Class Reference
Java API » Stream
Primary stream class.
Classes
interface Provider
Provider API for user-defined stream types.
interface Raise
Public Member Functions
long print (String format, Object... args) throws java.io.IOException
Prints a formatted string to the stream.
void release ()
Releases the native library handle.
int atEnd ()
Reports stream end status.
SnsrRC close ()
Closes an open stream.
long copy (SnsrStream src, long sizeInBytes) throws java.io.IOException
Copies from a stream.
String errorDetail ()
Retrieves a detailed stream error message.
long getDelim (byte[] buffer, int delim) throws java.io.IOException
Reads one line from the stream.
long getMeta (SnsrStreamMeta key)
Queries stream metadata.
SnsrRC open () throws java.io.IOException
Opens a stream.
SnsrRC rC ()
Retrieves the most recent return code for the stream.
long read (byte[] buffer, long offset, long count) throws java.io.IOException
Reads from a stream into a buffer at an offset.
long read (byte[] buffer) throws java.io.IOException
Reads from a stream, filling a buffer.
int read () throws java.io.IOException
Reads one byte from a stream.
long skip (long size, long nitems) throws java.io.IOException
Reads from a stream and discards the results.
long skip (long nitems) throws java.io.IOException
Reads from a stream and discards the results.
long write (byte[] buffer, long offset, long count) throws java.io.IOException
Writes from a buffer to the stream.
long write (byte[] buffer) throws java.io.IOException
Writes an entire buffer to the stream.
long write (int oneByte) throws java.io.IOException
Writes an single byte to the stream.
long copy (SnsrStream src) throws java.io.IOException
Copies all available data from a stream.
Static Public Member Functions
static SnsrStream fromAudioDevice (int sampleRate)
Streams live audio from an audio capture device.
static SnsrStream fromAudioDevice (int device, int sampleRate)
Streams live audio from an audio capture device.
static SnsrStream fromAudioDevice ()
Streams live audio at the default sample rate.
static SnsrStream fromProvider (SnsrStream.Provider custom, SnsrStreamMode mode)
Creates a read-only or write-only stream from a SnsrStream.Provider.
static SnsrStream fromProvider (SnsrStream.Provider custom)
Creates a read-write stream from a SnsrStream.Provider.
static SnsrStream fromFileName (String filename, String mode)
Wraps a stream around a stdio file.
static SnsrStream fromAudioFile (String filename, String mode)
Wraps a stream around a RIFF WAVE file.
static SnsrStream fromAudioStream (SnsrStream a, SnsrStreamAudioFormat format)
Converts stream audio format.
static SnsrStream fromBuffer (long initialSizeInBytes, long maxSizeInBytes)
Wraps a stream around a circular buffer.
static SnsrStream fromMemory (byte[] store, SnsrStreamMode mode)
Wraps a stream around a memory segment.
static SnsrStream fromOpenStream (SnsrStream source, long sizeInBytes)
Wraps a stream around an open stream.
static SnsrStream fromStreams (SnsrStream a, SnsrStream b)
Concatenates two streams.
static SnsrStream fromString (String store)
Wraps a stream around a read-only string.
Static Public Attributes
static int DEFAULT_SAMPLE_RATE = 16000
Default live audio capture sample rate.
Detailed Description
Primary stream class.
This section describes the stream abstraction through which all SnsrSession inputs and outputs are vectored.
The stream API is small and has well-defined semantics. Streams can be created on different underlying data streams (file names, handles, memory segments, live audio sources, and so on). Only the static constructor methods are type-specific, all other functions are independent of the underlying stream type. Operations that take SnsrStream handles as arguments operate on any of the types. The same recognition function, for example, could be used to recognize from file or live input.
No operations are done on the underlying data provider until SnsrStream.open() is called, and no operations are done after SnsrStream.close() has been called.
Note
The current implementation does not do any thread-level locking. Threaded access to stream handles must be protected by explicit synchronization calls.
Member Function Documentation
atEnd()
int atEnd ()
Reports stream end status.
Returns 1 if the stream has reached its end.
Follows Unix semantics:
The end-of-stream indicator is only valid after a read attempt.
A read on a SnsrStream b could very well return 0, even if snsrStreamAtEnd(b) returned 0 just before attempting the read.
Equivalent to
(SnsrStream.rC(b) == SnsrRC.EOF)
Returns
1 if at end-of-stream, 0 if not.
See also
SnsrStream.rC()
close()
SnsrRC close ()
Closes an open stream.
Any remaining buffered output is flushed.
Any remaining buffered input is discarded.
Closing a stream that is not open is not an error.
Streams that are still open when the last reference is removed are closed before the handle is released.
Returns
SnsrRC.OK for success, any other value indicates failure.
copy() [1/2]
long copy (SnsrStream src, long sizeInBytes) throws java.io.IOException
Copies from a stream.
Opens streams if they are not already open, copies sizeInBytes bytes from src, then returns the number of bytes successfully written. If an error occurred (including an end-of-stream condition) the return value will be less than sizeInBytes.
Parameters
src source stream.
sizeInBytes number of bytes to copy from src.
Returns
The number of bytes actually copied.
See also
SnsrStream.rC()
copy() [2/2]
long copy (SnsrStream src) throws java.io.IOException
Copies all available data from a stream.
Opens streams if they are not already open, copies all available bytes from src, then returns the number of bytes successfully copied.
Parameters
src source stream.
Returns
The number of bytes copied.
See also
SnsrStream.rC()
errorDetail()
String errorDetail ()
Retrieves a detailed stream error message.
This human-readable error message containing the reason for failure.
Use for display or logging only, as the content of the message is unspecified and system-specific.
Do not parse this to determine program flow, use the SnsrRC return code instead.
Returns
A detailed message describing the most recent reason for failure.
fromAudioDevice() [1/3]
static SnsrStream fromAudioDevice (int sampleRate) static
Streams live audio from an audio capture device.
Creates a new SnsrStream attached to the default audio capture device. The stream will return 16-bit LPCM encoded audio samples in little-endian byte order, sampled at sampleRate.
Parameters
sampleRate Audio capture sampling rate.
Returns
A new SnsrStream handle.
References SnsrStream.fromProvider(), and SnsrStreamMode.READ.
fromAudioDevice() [2/3]
static SnsrStream fromAudioDevice (int device, int sampleRate) static
Streams live audio from an audio capture device.
Creates a new SnsrStream attached to the specified audio capture device. The stream will return 16-bit LPCM encoded audio samples in little-endian byte order, sampled at sampleRate.
Note
Supported on Android only.
Parameters
device Audio device specifier.
sampleRate Audio capture sampling rate.
Returns
A new SnsrStream handle.
References SnsrStream.fromProvider(), and SnsrStreamMode.READ.
fromAudioDevice() [3/3]
static SnsrStream fromAudioDevice () static
Streams live audio at the default sample rate.
Creates a new SnsrStream attached to the default audio capture device. The stream will return 16-bit LPCM encoded audio samples in little-endian byte order, sampled at the default rate.
Equivalent to:
SnsrStream a = SnsrStream.fromAudioDevice(SnsrStream.DEFAULT_SAMPLE_RATE);
Returns
A new SnsrStream handle.
See also
SnsrStream::fromAudioDevice(int sampleRate)
References SnsrStream.DEFAULT_SAMPLE_RATE, and SnsrStream.fromAudioDevice().
fromAudioFile()
static SnsrStream fromAudioFile (String filename, String mode) static
Wraps a stream around a RIFF WAVE file.
This function is equivalent the code below, with the difference that the RIFF header is updated after each write to the stream.
SnsrStream s;
s = SnsrStream.fromAudioStream(SnsrStream.fromFileName(filename, mode),
                               SnsrStreamAudioFormat.DEFAULT);
Parameters
filename the name of the .wav file to open.
mode file access mode, r or w.
Returns
A new SnsrStream handle.
See also
SnsrStream::fromAudioStream(), SnsrStream::fromFileName().
fromAudioStream()
static SnsrStream fromAudioStream (SnsrStream a, SnsrStreamAudioFormat format) static
Converts stream audio format.
Creates a new SnsrStream on an existing stream, a. The new stream produces audio in format, converting as needed.
The audio format header in a will be read when the stream is first opened.
If this is a known, but unsupported format, SnsrStream::open() will report an error.
If the format is not known, the data in a will be treated as a headerless little-endian 16-bit LPCM stream.
The initial implementation supports the 16-bit LPCM RIFF Wave format, at 16 kHz sampling rate, for a single channel only.
Note
When this stream type is used for output, all stream data will be buffered in memory until the stream is closed. The audio header and the data will then be written to a, the wrapped SnsrStream.
Parameters
a source SnsrStream.
format output target format.
Returns
A new SnsrStream handle.
fromBuffer()
static SnsrStream fromBuffer (long initialSizeInBytes, long maxSizeInBytes) static
Wraps a stream around a circular buffer.
Creates a new SnsrStream on a circular buffer with first-in-first-out semantics. The initial buffer will be large enough to hold initialSizeInBytes bytes, and will dynamically grow up to maxSizeInBytes. If the SnsrStream the bufffer cannot be expanded, SnsrStream.write() will set the SnsrRC.EOF condition on the stream. This SnsrStream type does not support re-opening.
Note
SnsrStream.read() on streams of this type has non-blocking behavior, and will return SnsrRC.EOF if the buffer runs empty.
Parameters
initialSizeInBytes the minimum size of the allocated ring buffer.
maxSizeInBytes the limit the buffer is allowed to expand to.
Returns
A new SnsrStream handle.
fromFileName()
static SnsrStream fromFileName (String filename, String mode) static
Wraps a stream around a stdio file.
Creates a new SnsrStream using the <stdio.h> file functions.
Only a subset of the fopen() modes are supported:
r for read-only access.
w for write-only access, truncating the file to zero on open.
a for write-only append access.
mode supports an optional second character:
b for binary mode. This is the default if mode contains just one character.
t for text mode. On Windows this translates line-endings between \n and \r\n.
This stream type supports re-opening. The behavior follows that of fopen() with the given access mode.
Parameters
filename the name of a file to open.
mode r, w, or a, followed by optional b or t.
Returns
A new SnsrStream handle.
fromMemory()
static SnsrStream fromMemory (byte [] store, SnsrStreamMode mode) static
Wraps a stream around a memory segment.
Creates a new SnsrStream on memory segment store. This SnsrStream type does not support re-opening.
Note
Changes written through the SnsrStream API will not be visible in store until the SnsrStream instance has been released.
Read behavior is undefined if store is modified after the SnsrStream is instantiated.
Parameters
store data made available to the stream.
mode open for reading or writing, but not both.
Returns
A new SnsrStream handle.
See also
SnsrStream::fromString().
fromOpenStream()
static SnsrStream fromOpenStream (SnsrStream source, long sizeInBytes) static
Wraps a stream around an open stream.
Creates a new SnsrStream on an existing, open SnsrStream. The new stream mode (read or write) matches the source stream. Read and write operations are passed through to the source stream, but the number of bytes read or written is limited to sizeInBytes. In- and output operations will set the stream status to SnsrRC.EOF when this limit is reached.
Closing this SnsrStream instance will not close source.
Parameters
source source stream.
sizeInBytes new stream read or write limit.
Returns
A new SnsrStream handle.
fromProvider() [1/2]
static SnsrStream fromProvider (SnsrStream.Provider custom, SnsrStreamMode mode) static
Creates a read-only or write-only stream from a SnsrStream.Provider.
The returned stream is either read-only or write-only, as specified by the mode parameter.
Example:
public static SnsrStream fromAudioDevice(int sampleRate) {
  return SnsrStream.fromProvider(new SnsrStreamAudioDevice(sampleRate),
                               SnsrStreamMode.READ);
}
Parameters
custom plugin instance.
mode specifies whether the stream is read-only or write-only.
Returns
A new SnsrStream handle.
fromProvider() [2/2]
static SnsrStream fromProvider (SnsrStream.Provider custom) static
Creates a read-write stream from a SnsrStream.Provider.
The returned stream supports both reading and writing.
Parameters
custom plugin instance.
Returns
A new SnsrStream handle.
fromStreams()
static SnsrStream fromStreams (SnsrStream a, SnsrStream b) static
Concatenates two streams.
Creates a new SnsrStream that is a concatenation of a and b.
Streams a and b will be each be opened exactly once. These should be unopened (SnsrStream.getMeta() for SnsrStreamMeta.OPEN_COUNT must be 0) when SnsrStream.fromStreams() is called. This limitation does not apply to streams returned by this function, these can be nested to arbitrary depth to concatenate more than two streams.
The new stream will read from (or write to) a until end-of-stream is reached, then switch to stream b until that is exhausted, at which point SnsrRC.EOF is returned.
Streams a and b must have identical modes. If one stream was opened for reading, and the other for writing, this function will set the error code to SnsrRC.WRONG_MODE.
Closing this stream will close the current source stream. The next open call will open the next source stream. When no further source streams remain SnsrStream.open() returns SnsrRC.CANNOT_REOPEN.
Parameters
a first source stream.
b second source stream.
Returns
A new SnsrStream handle.
fromString()
static SnsrStream fromString (String store) static
Wraps a stream around a read-only string.
Creates a new SnsrStream from a zero-terminated String.
Note
Read behavior is undefined if store is modified after the SnsrStream is instantiated.
Parameters
store source data made available to the stream.
Returns
A new SnsrStream handle.
See also
SnsrStream::fromMemory().
getDelim()
long getDelim (byte [] buffer, int delim) throws java.io.IOException
Reads one line from the stream.
Reads a line from the stream, delimited by the character delim into buffer.
Opens the output stream if it is not already open.
Reads up to buffer.length - 1 bytes from the stream into buffer, stops when delim has been read (buffer will include delim).
Terminates the string in buffer with \0 and returns the number of characters read (not including the terminating \0).
If the delimiter is not found after reading buffer.length - 1 bytes, the stream error code is set to SnsrRC.DELIM_NOT_FOUND.
buffer.length >= 2 is required.
buffer will contain all characters read and will be terminated with \0, even if an error occurs.
Parameters
buffer destination buffer.
delim delimiter character to search for.
Returns
The number of characters read and placed into buffer.
getMeta()
long getMeta (SnsrStreamMeta key)
Queries stream metadata.
Returns stream metadata, selected by key. If an error occurs, this fuction returns 0 and sets the stream error state. Use SnsrStream.rC() to check stream state.
open()
SnsrRC open () throws java.io.IOException
Opens a stream.
Read and write operations are valid only on open streams.
Newly created streams are not open.
Streams are always opened in binary mode.
Some stream types can be closed and re-opened. This behavior is in the static constructor methods.
If re-opening is not supported SnsrStream.open() will return SnsrRC.CANNOT_REOPEN when an attempt is made to open it a second time.
Returns
SnsrRC.OK for success, any other value indicates failure.
Exceptions
IOException
print()
long print (String format, Object... args) throws java.io.IOException
Prints a formatted string to the stream.
Formats arguments according to Sting.format() rules, then writes this to the stream. Opens the output stream if it is not already open. If an error occurs, returns 0 and sets the stream error state. Use SnsrStream.rC() to check the stream state.
Parameters
format String.format type format specifier.
args as specified by the format specifier.
Returns
The number of bytes written to the stream.
See also
SnsrStream.rC()
rC()
SnsrRC rC ()
Retrieves the most recent return code for the stream.
Returns
The SnsrRC code for the stream.
read() [1/3]
long read (byte [] buffer, long offset, long count) throws java.io.IOException
Reads from a stream into a buffer at an offset.
Opens stream if it is not already open.
Reads count bytes into buffer at offset.
Returns the number of bytes read.
A short read (less than count) will occur only if the end of the stream was reached before count bytes were read, or if an error occurred. The stream return code will be set. Use SnsrStream.atEnd() or SnsrStream.rC() to distinguish between these conditions.
Read operations block until all the requested data have been read, or an error or end-of-stream is encountered.
Parameters
buffer destination byte[] buffer.
offset from the start of buffer where writing will commence.
count number of bytes to read from the stream.
Returns
The number of bytes read.
read() [2/3]
long read (byte [] buffer) throws java.io.IOException
Reads from a stream, filling a buffer.
Opens stream if it is not already open.
Reads bytes into buffer, attempts to fill the entire buffer.
Returns the number of bytes read.
A short read (less than buffer.length) will occur only if the end of the stream was reached before buffer.length bytes were read, or if an error occurred. The stream return code will be set. Use SnsrStream.atEnd()or SnsrStream.rC() to determine which occurred.
Read operations block until all the requested data have been read, or an error or end-of-stream is encountered.
Parameters
buffer destination byte[] buffer.
Returns
The number of bytes read.
read() [3/3]
int read () throws java.io.IOException
Reads one byte from a stream.
Opens stream if it is not already open.
Returns the value of the byte read, or Integer.MIN_VALUE if an error occurred.
If the end of the stream was reached, or an error occurred, the stream return code status will be set. Use SnsrStream.atEnd() or SnsrStream.rC() to distinguish between these conditions.
Read operations block until a byte has been read, or an error or end-of-stream is encountered.
Returns
The number of bytes read.
release()
void release ()
Releases the native library handle.
This method releases the underlying native handles immediately. Use this to free up resources without having to depend on garbage collection.
Note
No instance methods must be invoked after calling this method.
Recommended use:
SnsrStream s = SnsrStream.fromAudioDevice();
s.release();
s = null;
skip() [1/2]
long skip (long size, long nitems) throws java.io.IOException
Reads from a stream and discards the results.
Opens stream if it is not already open, reads nitems, each of size size from the stream and discards the read data. Returns the number of items (not bytes) read.
Parameters
size the size of an item, in bytes.
nitems the number of items to read and discard.
Returns
The number of items read.
See also
SnsrStream.read()
skip() [2/2]
long skip (long nitems) throws java.io.IOException
Reads from a stream and discards the results.
Opens stream if it is not already open, reads nitems bytes from the stream and discards the read data. Returns the number of bytes read.
Parameters
nitems the number of bytes to read and discard.
Returns
The number of bytes read.
See also
SnsrStream.read()
write() [1/3]
long write (byte [] buffer, long offset, long count) throws java.io.IOException
Writes from a buffer to the stream.
Opens stream if it is not already open.
Writes count bytes to the stream obtaining them from buffer starting at offset bytes. Returns the number of bytes written.
Returns less than count only if an error occurred. Use SnsrStream.rC() to obtain the error code.
Write operations block until the requested data have been transferred to the underlying implementation, but may return well before the data have reached their final destination (written to disk, played from a speaker, etc.)
Parameters
buffer source byte[] buffer.
offset from the start of buffer where reading will start.
count number of bytes to write.
Returns
The number of bytes written.
write() [2/3]
long write (byte [] buffer) throws java.io.IOException
Writes an entire buffer to the stream.
Opens stream if it is not already open.
Writes buffer.length bytes to the stream obtaining them from buffer Returns the number of bytes written.
Returns less than buffer.length only if an error occurred. Use SnsrStream.rC() to obtain the error code.
Write operations block until the requested data have been transferred to the underlying implementation, but may return well before the data have reached their final destination (written to disk, played from a speaker, etc.)
Parameters
buffer source byte[] buffer.
Returns
The number of bytes written.
write() [3/3]
long write (int oneByte) throws java.io.IOException
Writes an single byte to the stream.
Opens stream if it is not already open.
Writes oneByte to the stream.
The stream return code will be set if and end-of-stream condition or other error occurred. Use SnsrStream.rC() to obtain the error code.
Write operations block until the requested data have been transferred to the underlying implementation, but may return well before the data have reached their final destination (written to disk, played from a speaker, etc.)
Parameters
oneByte a single source byte.
Returns
The number of bytes written - either zero or one.
Member Data Documentation
DEFAULT_SAMPLE_RATE
int DEFAULT_SAMPLE_RATE = 16000 static
Default live audio capture sample rate.
The documentation for this class was generated from the following file:
SnsrStream.java